### ISSUE TITLE
Peer to peer code review 25/02/2022

### ISSUE THREAD

**Issue by vikipretium** [carlylechia/My-To-do-List#4]
### Feedback 
- The project is working perfectly and UI and UX are really good. I also noticed that you are in the progress of implementing the drag and drop feature to the app. It would be great to see that feature in the app. 
- A small change about the index of the list. Please check the list index starts with 1 instead of 0.

**Comment by carlylechia** [comment]
Thank you guys so much; this issue has been handled.
